version: "3.8"
services:
  studio:
    image: supabase/studio:20230629-c67f469
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: Supabase123$
      DEFAULT_ORGANIZATION: eliya789@gmail.com's1.Org
      PROJECT_ID: lpyyfflzfumyihkshfct

  db:
    image: supabase/postgres:14.1.0.34
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Supabase123$

  meta:
    image: supabase/postgres-meta:v0.68.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PASSWORD: Supabase123$
