# Netlify configuration for a Vite + React app
# - Reproducible installs with npm ci
# - Publish Vite output from /dist
# - Pin Node to a modern LTS for Vite 5
# - SPA-style routing fallback

[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Single Page App fallback so client-side routes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
